// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(AdminContext))]
    [Migration("20211028093635_createDb")]
    partial class createDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entites.Address.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProvceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProvceId");

                    b.ToTable("Cites");
                });

            modelBuilder.Entity("DataLayer.Entites.Address.Provce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.HasKey("Id");

                    b.ToTable("Provce");
                });

            modelBuilder.Entity("DataLayer.Entites.Address.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("DataLayer.Entites.Banner.Banners", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Link")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("DataLayer.Entites.Colleagueandconsultants.Colleage_Care", b =>
                {
                    b.Property<int>("Colleage_Careid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CareAndMaintenanceId")
                        .HasColumnType("int");

                    b.Property<int>("ColleagueAndConsultantsId")
                        .HasColumnType("int");

                    b.HasKey("Colleage_Careid");

                    b.HasIndex("CareAndMaintenanceId");

                    b.HasIndex("ColleagueAndConsultantsId");

                    b.ToTable("Colleage_Cares");
                });

            modelBuilder.Entity("DataLayer.Entites.Colleagueandconsultants.Colleage_Rehabilitation", b =>
                {
                    b.Property<int>("ColleageRehabilitationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColleagueAndConsultantsId")
                        .HasColumnType("int");

                    b.Property<int>("RehabilitationAndSpeechtherapyId")
                        .HasColumnType("int");

                    b.HasKey("ColleageRehabilitationid");

                    b.HasIndex("ColleagueAndConsultantsId");

                    b.HasIndex("RehabilitationAndSpeechtherapyId");

                    b.ToTable("Colleage_Rehabilitations");
                });

            modelBuilder.Entity("DataLayer.Entites.Colleagueandconsultants.ColleagueAndConsultants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Famaily")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Mobaile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("ProvceId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvceId");

                    b.ToTable("ColleagueAndConsultants");
                });

            modelBuilder.Entity("DataLayer.Entites.HospitalServices.CTScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscreaptionAdmin")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("cooperationbenefits")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("CTScan");
                });

            modelBuilder.Entity("DataLayer.Entites.HospitalServices.Radiology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscreaptionAdmin")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("cooperationbenefits")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Radiology");
                });

            modelBuilder.Entity("DataLayer.Entites.HospitalServices.sonography", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscreaptionAdmin")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("cooperationbenefits")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("sonography");
                });

            modelBuilder.Entity("DataLayer.Entites.Media.SocialNetworks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Link")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("SocialNetworks");
                });

            modelBuilder.Entity("DataLayer.Entites.Pages.AboutUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Title")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutUs");
                });

            modelBuilder.Entity("DataLayer.Entites.Pages.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Title")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("DataLayer.Entites.Pages.RulesOfRegulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Title")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RulesOfRegulation");
                });

            modelBuilder.Entity("DataLayer.Entites.ServicesNurse.CareAndMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscreaptionAdmin")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("nvarchar(900)");

                    b.HasKey("Id");

                    b.ToTable("CareAndMaintenances");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CareAndMaintenance");
                });

            modelBuilder.Entity("DataLayer.Entites.ServicesNurse.ServiceNures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscreaptionAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Needadvice")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("cooperationbenefits")
                        .HasColumnType("tinyint");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceNures");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("IssueTrackingNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<double>("PayAmount")
                        .HasColumnType("float");

                    b.Property<long>("RefId")
                        .HasColumnType("bigint");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<byte>("Rentaltime")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("WillRenew")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreaCreatetionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discreaption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("DataLayer.Entites.ServicesNurse.RehabilitationAndSpeechtherapy", b =>
                {
                    b.HasBaseType("DataLayer.Entites.ServicesNurse.CareAndMaintenance");

                    b.HasDiscriminator().HasValue("RehabilitationAndSpeechtherapy");
                });

            modelBuilder.Entity("DataLayer.Entites.Address.City", b =>
                {
                    b.HasOne("DataLayer.Entites.Address.Provce", "Provce")
                        .WithMany("Cities")
                        .HasForeignKey("ProvceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provce");
                });

            modelBuilder.Entity("DataLayer.Entites.Address.Region", b =>
                {
                    b.HasOne("DataLayer.Entites.Address.City", "City")
                        .WithMany("Regions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DataLayer.Entites.Colleagueandconsultants.Colleage_Care", b =>
                {
                    b.HasOne("DataLayer.Entites.ServicesNurse.CareAndMaintenance", "CareAndMaintenance")
                        .WithMany("Colleage_Cares")
                        .HasForeignKey("CareAndMaintenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entites.Colleagueandconsultants.ColleagueAndConsultants", "ColleagueAndConsultants")
                        .WithMany("Colleage_Cares")
                        .HasForeignKey("ColleagueAndConsultantsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareAndMaintenance");

                    b.Navigation("ColleagueAndConsultants");
                });

            modelBuilder.Entity("DataLayer.Entites.Colleagueandconsultants.Colleage_Rehabilitation", b =>
                {
                    b.HasOne("DataLayer.Entites.Colleagueandconsultants.ColleagueAndConsultants", "ColleagueAndConsultants")
                        .WithMany("Colleage_Rehabilitations")
                        .HasForeignKey("ColleagueAndConsultantsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entites.ServicesNurse.RehabilitationAndSpeechtherapy", "CareAndMaintenance")
                        .WithMany("Colleage_Rehabilitations")
                        .HasForeignKey("RehabilitationAndSpeechtherapyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareAndMaintenance");

                    b.Navigation("ColleagueAndConsultants");
                });

            modelBuilder.Entity("DataLayer.Entites.Colleagueandconsultants.ColleagueAndConsultants", b =>
                {
                    b.HasOne("DataLayer.Entites.Address.City", "City")
                        .WithMany("ColleagueAndConsultants")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entites.Address.Provce", "Provce")
                        .WithMany("ColleagueAndConsultants")
                        .HasForeignKey("ProvceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Provce");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.OrderItem", b =>
                {
                    b.HasOne("DataLayer.Entites.Store.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.Product", b =>
                {
                    b.HasOne("DataLayer.Entites.Store.ProductCategory", "ProductCategory")
                        .WithMany("Prouducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("DataLayer.Entites.Address.City", b =>
                {
                    b.Navigation("ColleagueAndConsultants");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("DataLayer.Entites.Address.Provce", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("ColleagueAndConsultants");
                });

            modelBuilder.Entity("DataLayer.Entites.Colleagueandconsultants.ColleagueAndConsultants", b =>
                {
                    b.Navigation("Colleage_Cares");

                    b.Navigation("Colleage_Rehabilitations");
                });

            modelBuilder.Entity("DataLayer.Entites.ServicesNurse.CareAndMaintenance", b =>
                {
                    b.Navigation("Colleage_Cares");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DataLayer.Entites.Store.ProductCategory", b =>
                {
                    b.Navigation("Prouducts");
                });

            modelBuilder.Entity("DataLayer.Entites.ServicesNurse.RehabilitationAndSpeechtherapy", b =>
                {
                    b.Navigation("Colleage_Rehabilitations");
                });
#pragma warning restore 612, 618
        }
    }
}
